<?php

return [

    'default' => 'db_project_management', 
    'connections' => [
        'db_af' => [
            'driver' => 'pgsql',
            'host' => env('DB_AF_HOST', 'localhost'),
            'port' => env('DB_AF_PORT', '1433'),
            'database' => env('DB_AF_DATABASE', 'forge'),
            'username' => env('DB_AF_USERNAME', 'forge'),
            'password' => env('DB_AF_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
        ],
        'db_project_management' => [
            'driver' => 'pgsql',
            'host' => env('DB_PM_HOST', 'localhost'),
            'port' => env('DB_PM_PORT', '1433'),
            'database' => env('DB_PM_DATABASE', 'forge'),
            'username' => env('DB_PM_USERNAME', 'forge'),
            'password' => env('DB_PM_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
        ],
        'db_hr' => [
            'driver' => 'pgsql',
            'host' => env('DB_HR_HOST', 'localhost'),
            'port' => env('DB_HR_PORT', '1433'),
            'database' => env('DB_HR_DATABASE', 'forge'),
            'username' => env('DB_HR_USERNAME', 'forge'),
            'password' => env('DB_HR_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
        ],
        'db_xl' => [
            'driver' => 'pgsql',
            'host' => env('DB_XL_HOST', 'localhost'),
            'port' => env('DB_XL_PORT', '1433'),
            'database' => env('DB_XL_DATABASE', 'forge'),
            'username' => env('DB_XL_USERNAME', 'forge'),
            'password' => env('DB_XL_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],
        'db_isat' => [
            'driver' => 'pgsql',
            'host' => env('DB_ISAT_HOST', 'localhost'),
            'port' => env('DB_ISAT_PORT', '1433'),
            'database' => env('DB_ISAT_DATABASE', 'forge'),
            'username' => env('DB_ISAT_USERNAME', 'forge'),
            'password' => env('DB_ISAT_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],
    ],
];